# Generated by Django 2.1.3 on 2018-11-25 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamsapp', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='team',
            field=models.ForeignKey(default=2, on_delete='cascade', to='teamsapp.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 15, 59, 31, 256998, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 15, 59, 31, 258146, tzinfo=utc)),
        ),
    ]
