# Generated by Django 2.1.3 on 2018-11-25 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181125_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
