# Generated by Django 2.1.3 on 2018-11-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsapp', '0006_auto_20181127_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='team',
            new_name='teams',
        ),
    ]
